version: "2"
services:
  httpd:
    container_name: wp_httpd
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.data/nginx:/var/log/nginx
      - ../public:/var/www/html

  php:
    container_name: wp_php
    build: ./php-fpm
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../Movefile:/Movefile
      - ./.data/php:/var/log/php
      - ../public:/var/www/html

  db:
    container_name: wp_db
    image: mysql:5.7
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
